### ISSUE TITLE
getVisitorId crashing after fingerprintjs (non-pro) update to 2.0.0

### ISSUE THREAD

**Issue by AndreasBoehm** [fingerprintjs/fingerprintjs-pro-android-demo#28]
After upgrading to the latest version of fingerprintjs (2.0.0) the app is crashing when i call `getVisitorId`

Due to the obfuscation of the fingerprintjs-pro library i wasn't able to further debug this.

```
java.lang.IncompatibleClassChangeError: Found class com.fingerprintjs.android.fingerprint.Fingerprinter, but interface was expected (declaration of 'com.fingerprintjs.android.fingerprint.Fingerprinter' appears in /data/app/~~DEmI_3A1HPIABj3UBZtjvg==/x.x.x-6hyMKHGxsQLqIkAf3LIkhQ==/base.apk!classes19.dex)
                                                                                                    	at fpproc.e.invoke(SourceFile:1)
                                                                                                    	at fpprof.b.a(Unknown Source:10)
                                                                                                    	at fpproc.j.a(SourceFile:1)
                                                                                                    	at fpproc.j$$ExternalSyntheticLambda0.run(Unknown Source:10)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Alexey-Verkhovsky** [comment]
Hello! Thanks for the report. It's our issue. If it's possible, keep the OSS version 1.3.0 (Anyway 2.0.0 does not contain new crucial functionality besides the API change so that's should be possible), we'll prepare the update soon.

**Comment by Alexey-Verkhovsky** [comment]
@AndreasBoehm The update is ready. Update the PRO version to 2.2.1, everything should work. Please, reopen the issue if the problem still exists.

**Comment by AndreasBoehm** [comment]
Thanks @Alexey-Verkhovsky, its working fine now.
